/**
 * Generates the ELP 2000-82B lunar series we ship.
 *
 * ELP 2000-82B is the Bureau des Longitudes lunar theory (Chapront-Touze &
 * Chapront), with constants fitted to JPL's DE200/LE200. Like VSOP87 the
 * coefficients are published reference constants, fetched rather than typed.
 *
 * Source: https://cdsarc.cds.unistra.fr/ftp/VI/79/  (catalogue VI/79)
 *
 * The theory arrives as 36 files in three record layouts, and which layout a
 * file uses - and which power of time its amplitude carries - is decided by
 * the file's number. That grouping is not ours to redesign: it is reproduced
 * from the reference implementation elp82b.f, and the runtime applies the same
 * rules. Nothing is truncated; the whole theory is small enough to keep.
 *
 * Run with:  npx tsx scripts/astronomy/build-elp.ts
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const CATALOGUE = "https://cdsarc.cds.unistra.fr/ftp/VI/79";
const OUT_DIR = path.join(process.cwd(), "src/lib/astrology/engine/data");

/** Files 1-3 are the main problem, 10-21 the planetary perturbations, the rest are the others. */
const MAIN_FILES = [1, 2, 3];
const PLANETARY_FILES = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21];

/** Fixed-column slice to a number. FORTRAN records are positional, not delimited. */
function field(line: string, start: number, end: number): number {
  const text = line.slice(start - 1, end).trim();
  if (text === "") return 0;
  const value = Number(text);
  if (!Number.isFinite(value)) throw new Error(`unparseable field [${start},${end}] in: ${line}`);
  return value;
}

/** Main problem, FORTRAN format 4i3,2x,f13.5,6(2x,f10.2). */
function parseMain(line: string): number[] {
  const record = [field(line, 1, 3), field(line, 4, 6), field(line, 7, 9), field(line, 10, 12), field(line, 15, 27)];
  for (let i = 0; i < 6; i += 1) {
    const start = 30 + i * 12;
    record.push(field(line, start, start + 9));
  }
  return record;
}

/** Figures, tides, relativity, solar eccentricity. Format 5i3,1x,f9.5,1x,f9.5,1x,f9.3. */
function parsePerturbation(line: string): number[] {
  return [
    field(line, 1, 3),
    field(line, 4, 6),
    field(line, 7, 9),
    field(line, 10, 12),
    field(line, 13, 15),
    field(line, 17, 25),
    field(line, 27, 35),
  ];
}

/** Planetary perturbations. Format 11i3,1x,f9.5,1x,f9.5,1x,f9.3. */
function parsePlanetary(line: string): number[] {
  const record: number[] = [];
  for (let i = 0; i < 11; i += 1) record.push(field(line, 1 + i * 3, 3 + i * 3));
  record.push(field(line, 35, 43), field(line, 45, 53));
  return record;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const blocks: string[] = [];
  let grandTotal = 0;

  for (let file = 1; file <= 36; file += 1) {
    const response = await fetch(`${CATALOGUE}/ELP${file}`);
    if (!response.ok) throw new Error(`ELP${file} responded ${response.status}`);
    // The first line is a title, every line after it is a record.
    const lines = (await response.text()).split("\n").slice(1).filter((line) => line.trim() !== "");

    const parse = MAIN_FILES.includes(file)
      ? parseMain
      : PLANETARY_FILES.includes(file)
        ? parsePlanetary
        : parsePerturbation;

    const flat: number[] = [];
    for (const line of lines) flat.push(...parse(line));

    grandTotal += lines.length;
    blocks.push(`  ${file}: [${flat.join(",")}],`);
    console.log(`ELP${String(file).padStart(2)}  ${String(lines.length).padStart(5)} terms`);
  }

  const out = `// Generated by scripts/astronomy/build-elp.ts - do not edit by hand.
//
// ELP 2000-82B lunar theory. Source: Bureau des Longitudes, CDS catalogue VI/79.
// Constants fitted to JPL DE200/LE200.
//
// Keyed by the theory's own file number, because which record layout applies -
// and which power of time multiplies the amplitude - is decided by that number.
// Records are flattened; the stride depends on the layout:
//
//   files 1-3    main problem, stride 11: i1 i2 i3 i4 then 7 coefficients
//   files 10-21  planetary,    stride 13: 11 multipliers, phase, amplitude
//   all others   stride 7:     iz i1 i2 i3 i4, phase, amplitude
//
// ${grandTotal} terms in total, the complete untruncated theory.

export const ELP_SERIES: Record<number, readonly number[]> = {
${blocks.join("\n")}
};
`;
  await writeFile(path.join(OUT_DIR, "elp2000-82b.ts"), out);
  console.log(`total ${grandTotal} terms`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
