/**
 * Generates the observed delta-T table.
 *
 * Delta-T (TT - UT) is the accumulated difference between the Earth's actual
 * rotation and uniform time. It cannot be predicted from theory - the Earth is
 * not a good clock - so for the era where it has been measured, measurements
 * are the only honest source.
 *
 * Outside the observed era the engine falls back to the Espenak & Meeus
 * polynomials, which are fits to historical eclipse records before 1600 and
 * extrapolation after the present. That extrapolation is what the table
 * replaces: at 2026 the polynomial overshoots by about six seconds, which is
 * the single largest error term left in the lunar position.
 *
 *   delta-T = 32.184 + (TAI - UTC) - (UT1 - UTC)
 *
 * Sources:
 *   UT1-UTC   IERS finals.all              https://maia.usno.navy.mil/ser7/finals.all
 *   TAI-UTC   IANA leap second list        https://data.iana.org/time-zones/data/leap-seconds.list
 *
 * Run with:  npx tsx scripts/astronomy/build-delta-t.ts
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

const FINALS = "https://maia.usno.navy.mil/ser7/finals.all";
const LEAP_SECONDS = "https://data.iana.org/time-zones/data/leap-seconds.list";
const OUT = path.join(process.cwd(), "src/lib/astrology/engine/data/delta-t.ts");

/** Seconds between the NTP epoch (1900) and the Unix epoch (1970). */
const NTP_TO_UNIX = 2208988800;

/** Modified Julian Date of the Unix epoch. */
const MJD_UNIX_EPOCH = 40587;

async function leapSeconds(): Promise<{ mjd: number; taiMinusUtc: number }[]> {
  const text = await (await fetch(LEAP_SECONDS)).text();
  const entries: { mjd: number; taiMinusUtc: number }[] = [];
  for (const line of text.split("\n")) {
    if (!/^\d/.test(line)) continue;
    const [ntp, value] = line.trim().split(/\s+/);
    const unixSeconds = Number(ntp) - NTP_TO_UNIX;
    entries.push({ mjd: MJD_UNIX_EPOCH + unixSeconds / 86400, taiMinusUtc: Number(value) });
  }
  return entries.sort((a, b) => a.mjd - b.mjd);
}

function taiMinusUtcAt(mjd: number, table: { mjd: number; taiMinusUtc: number }[]): number | null {
  let value: number | null = null;
  for (const entry of table) {
    if (mjd >= entry.mjd) value = entry.taiMinusUtc;
    else break;
  }
  return value;
}

async function main() {
  const leaps = await leapSeconds();
  const finals = await (await fetch(FINALS)).text();

  const samples: [number, number][] = [];
  let lastSampledMjd = -Infinity;

  for (const line of finals.split("\n")) {
    if (line.length < 68) continue;
    // Only rows flagged 'I' are final IERS values; 'P' rows are predictions.
    if (line[57] !== "I") continue;

    const mjd = Number(line.slice(7, 15));
    const ut1MinusUtc = Number(line.slice(58, 68));
    if (!Number.isFinite(mjd) || !Number.isFinite(ut1MinusUtc)) continue;

    // One sample a month is ample: delta-T moves by under a second a year.
    if (mjd - lastSampledMjd < 30) continue;

    const tai = taiMinusUtcAt(mjd, leaps);
    if (tai === null) continue;

    samples.push([mjd, Number((32.184 + tai - ut1MinusUtc).toFixed(4))]);
    lastSampledMjd = mjd;
  }

  if (samples.length < 100) throw new Error(`only ${samples.length} delta-T samples parsed; format may have changed`);

  const first = samples[0];
  const last = samples[samples.length - 1];
  const asDate = (mjd: number) => new Date((mjd - MJD_UNIX_EPOCH) * 86400000).toISOString().slice(0, 10);

  const out = `// Generated by scripts/astronomy/build-delta-t.ts - do not edit by hand.
//
// Observed delta-T (TT - UT) in seconds, sampled monthly, as
// 32.184 + (TAI - UTC) - (UT1 - UTC).
//
// Sources: IERS finals.all (UT1-UTC, final values only) and the IANA leap
// second list (TAI-UTC). Covers ${asDate(first[0])} to ${asDate(last[0])};
// ${samples.length} samples, ${first[1]}s rising to ${last[1]}s.
//
// Pairs of [Modified Julian Date, delta-T seconds].

export const OBSERVED_DELTA_T: readonly (readonly [number, number])[] = [
${samples.map(([mjd, dt]) => `  [${mjd}, ${dt}],`).join("\n")}
];
`;
  await writeFile(OUT, out);
  console.log(`${samples.length} samples, ${asDate(first[0])} (${first[1]}s) to ${asDate(last[0])} (${last[1]}s)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
