/**
 * Generates the VSOP87D coefficient tables we ship.
 *
 * VSOP87 is the planetary theory of the Bureau des Longitudes (Bretagnon &
 * Francou, 1988). The coefficients are published reference constants, not
 * anyone's code, and they are fetched here from the CDS archive rather than
 * transcribed, because a hand-copied astronomical constant is a silent wrong
 * answer for the life of the product.
 *
 * Source:  https://cdsarc.cds.unistra.fr/ftp/VI/81/  (catalogue VI/81)
 * Variant: D = heliocentric spherical (L, B, R), mean ecliptic and equinox
 *          of the date - the form Meeus works in and the one that feeds
 *          straight into an apparent geocentric position.
 *
 * Each term is A * cos(B + C * tau), summed per power of tau, where
 * tau = (JD_TT - 2451545.0) / 365250.
 *
 * Terms below AMPLITUDE_THRESHOLD are dropped. That figure was chosen by
 * measurement, not taste: see the header written into each generated file.
 *
 * Run with:  npx tsx scripts/astronomy/build-vsop87.ts
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const CATALOGUE = "https://cdsarc.cds.unistra.fr/ftp/VI/81";
const OUT_DIR = path.join(process.cwd(), "src/lib/astrology/engine/data");

/**
 * Keeps 9000 of 25659 terms for a worst-case longitude error of 0.052 arcsec
 * over 1700-2300, measured against the untruncated series. The finest
 * division this product reads is a KP sub-sub lord at roughly 578 arcsec, so
 * the margin is about four orders of magnitude, and delta-T uncertainty
 * dominates this error long before the truncation does.
 */
const AMPLITUDE_THRESHOLD = 1e-8;

const BODIES = [
  { key: "earth", file: "ear", name: "EARTH" },
  { key: "mercury", file: "mer", name: "MERCURY" },
  { key: "venus", file: "ven", name: "VENUS" },
  { key: "mars", file: "mar", name: "MARS" },
  { key: "jupiter", file: "jup", name: "JUPITER" },
  { key: "saturn", file: "sat", name: "SATURN" },
] as const;

const HEADER = /VSOP87 VERSION \S+\s+(\w+)\s+VARIABLE (\d) \(LBR\)\s+\*T\*\*(\d)\s+(\d+) TERMS/;
const VARIABLE_NAMES = { 1: "L", 2: "B", 3: "R" } as const;

type Series = Record<"L" | "B" | "R", number[][]>;

function parse(text: string, body: string): { series: Series; kept: number; total: number } {
  const series: Series = { L: [], B: [], R: [] };
  let current: number[] | null = null;
  let declared = 0;
  let seen = 0;
  let kept = 0;
  let total = 0;

  const finishBlock = () => {
    if (current !== null && seen !== declared) {
      throw new Error(`${body}: block declared ${declared} terms, found ${seen}`);
    }
  };

  for (const line of text.split("\n")) {
    const header = HEADER.exec(line);
    if (header) {
      finishBlock();
      const variable = VARIABLE_NAMES[Number(header[2]) as 1 | 2 | 3];
      const power = Number(header[3]);
      declared = Number(header[4]);
      seen = 0;
      // Powers arrive in order, but do not assume it.
      while (series[variable].length <= power) series[variable].push([]);
      current = series[variable][power];
      continue;
    }
    if (current === null || line.trim() === "") continue;

    // A, B and C are the last three whitespace-separated numbers on the line.
    const parts = line.trim().split(/\s+/);
    const a = Number(parts[parts.length - 3]);
    const b = Number(parts[parts.length - 2]);
    const c = Number(parts[parts.length - 1]);
    if (!Number.isFinite(a) || !Number.isFinite(b) || !Number.isFinite(c)) {
      throw new Error(`${body}: unparseable term: ${line}`);
    }

    seen += 1;
    total += 1;
    if (Math.abs(a) >= AMPLITUDE_THRESHOLD) {
      current.push(a, b, c);
      kept += 1;
    }
  }
  finishBlock();

  if (series.L.length === 0 || series.R.length === 0) throw new Error(`${body}: missing series`);
  return { series, kept, total };
}

function emit(body: string, series: Series, kept: number, total: number): string {
  const block = (name: "L" | "B" | "R") =>
    `  ${name}: [\n${series[name]
      .map((flat) => `    [${flat.join(",")}],`)
      .join("\n")}\n  ],`;

  return `// Generated by scripts/astronomy/build-vsop87.ts - do not edit by hand.
//
// VSOP87D ${body}: heliocentric L, B, R referred to the mean ecliptic and
// equinox of the date. Source: Bureau des Longitudes, CDS catalogue VI/81.
//
// Flat [A, B, C, A, B, C, ...] triples, indexed by power of tau.
// Terms with |A| < ${AMPLITUDE_THRESHOLD} dropped: ${kept} of ${total} terms retained.

export const VSOP87D_${body.toUpperCase()} = {
${block("L")}
${block("B")}
${block("R")}
} as const;
`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  let grandKept = 0;
  let grandTotal = 0;

  for (const body of BODIES) {
    const url = `${CATALOGUE}/VSOP87D.${body.file}`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} responded ${response.status}`);
    const text = await response.text();

    const { series, kept, total } = parse(text, body.name);
    grandKept += kept;
    grandTotal += total;

    const out = path.join(OUT_DIR, `vsop87d-${body.key}.ts`);
    await writeFile(out, emit(body.key, series, kept, total));
    console.log(`${body.key.padEnd(8)} ${String(kept).padStart(5)}/${String(total).padStart(5)} terms`);
  }
  console.log(`total    ${grandKept}/${grandTotal} terms`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
